#! /bin/sh

sxhkd &

dunst &

feh --bg-fill /home/coder/Downloads/nord.png

# Cursor
xsetroot -cursor_name left_ptr & 

# Startup
"${HOME}/.config/bspwm/startup.sh"

#Capture of displays to envs
export monitor1=$(xrandr |grep ' connected'|sed -n 1p|awk '{print $1}')
export monitor2=$(xrandr |grep ' connected'|sed -n 2p|awk '{print $1}')

#Xrandr for HDMI, alter mode for others reslutions
mode=1920x1080
if [[ -z $monitor2 ]]; then
  xrandr --output "$monitor1" --mode "$mode" --primary
  bspc monitor "$monitor1" -d term chat www archiver code media discord slack tester
else
  xrandr --output "$monitor1" --mode "$mode" --primary
  bspc monitor "$monitor1" -d term chat www archiver code media discord slack tester
  xrandr --output "$monitor2" --auto --right-of $monitor1
  bspc monitor "$monitor2" -d term chat www archiver code media discord slack tester
fi

bspc config border_width            1
bspc config window_gap              6

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config pointer_follows_focus   false
bspc config focus_follows_pointer   true
bspc config center_pseudo_tiled     true

bspc config focused_border_color  "#FFFFFF"
bspc config normal_border_color   "#2E3440"
bspc config presel_feedback_color "#FFFFFF"

bspc rule -a kitty            desktop='^1'
bspc rule -a TelegramDesktop  desktop='^2'
bspc rule -a Chromium         desktop='^3' floating=true
bspc rule -a Thunar           desktop='^4'
bspc rule -a Code             desktop='^5' 
bspc rule -a vlc              desktop='^6'
bspc rule -a discord          desktop='^7'
bspc rule -a insomnia         desktop='^8'
bspc rule -a Slack            desktop='^9'

# Polybar
~/.config/polybar/launch.sh

# Scripts
~/.config/scripts/bat.sh